server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://10.10.10.40:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_project']
        target_label: 'compose_project'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'compose_service'
      - target_label: 'server'
        replacement: 'reranker'
      - target_label: 'hostname'
        replacement: 'reranker'
      - target_label: 'job'
        replacement: 'docker-logs'

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          server: reranker
          hostname: reranker
          __path__: /var/log/*log
